DROP TABLE IF EXISTS CIDADE;
 
CREATE TABLE CIDADE (
  ID INT auto_increment  PRIMARY KEY,
  NOME VARCHAR(250) NOT NULL,
  ESTADO VARCHAR(250) NOT NULL

);

DROP TABLE IF EXISTS CLIENTE;
 
CREATE TABLE CLIENTE (
  ID INT auto_increment  PRIMARY KEY,
  NOME VARCHAR(250) NOT NULL,
  SEXO VARCHAR(15) NOT NULL,
  DT_NASCIMENTO DATE,
  IDADE INT,
  ID_CIDADE INT,
  FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);